name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # Stick to Ubuntu 22.04 for now

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Ensure required directories exist
      - name: Ensure required directories exist
        run: |
          mkdir -p data
          mkdir -p metadata
          mkdir -p downloads

      # Step 4: Set up a virtual environment and install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          . venv/bin/activate
          pytest tests/
